### ISSUE TITLE
Installing GeoUsage Test requirements fail for cryptography package

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoUsage#2]
After installing GeoUsage, I tried to install and run the tests.

With `pip install -r requirements-dev.txt`, I got the following error:
```
...
Downloading/unpacking cryptography>=2.2.1 (from pyOpenSSL->-r requirements-dev.txt (line 12))
  Downloading cryptography-2.3.1.tar.gz (449kB): 449kB downloaded
  Running setup.py (path:/REMOVED/GeoUsage/build/cryptography/setup.py) egg_info for package cryptography
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "REMOVED/GeoUsage/build/cryptography/setup.py", line 28, in <module>
        "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "REMOVED/GeoUsage/build/cryptography/setup.py", line 28, in <module>

    "cryptography requires setuptools 18.5 or newer, please upgrade to a "

RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /REMOVED/GeoUsage/build/cryptography
Storing debug log for failure in /REMOVED/.pip/pip.log
```

Please advise. Thanks!

**Comment by tomkralidis** [comment]
Looks like a newer version of setuptools is required.  If you are not able to upgrade setuptools system wide, try the below (worked for me in a Python 2 virtualenv):

```bash
# upgrade setuptools 
pip install setuptools -U  # you will see some compile errors, but carry on
# install dev dependencies
pip install -r requirements-dev.txt
```

**Comment by alexandreleroux** [comment]
Thanks @tomkralidis . Using `pip install setuptools -U` doesn't seem to work for me. I get the following error:
```
/trash$ pip install setuptools -U
Downloading/unpacking setuptools from https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl#sha256=ce4137d58b444bac11a31d4e0c1805c69d89e8ed4e91fde1999674ecc2f6f9ff
  Downloading setuptools-40.4.3-py2.py3-none-any.whl (569kB): 569kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
  Can't roll back setuptools; was not uninstalled
```

Any advice or solution? Thanks!

**Comment by alexandreleroux** [comment]
Update: I ran `pip install setuptools -U` but in the virtualenv this time and I was able to go further.

However, when running `pip install -r requirements-dev.txt` in this virtualenv, I got a new error:
```
creating build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/PATH/GeoUsage/include/python3.4m -c build/temp.linux-x86_64-3.4/_openssl.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_openssl.o -Wconversion -Wno-error=sign-conversion

build/temp.linux-x86_64-3.4/_openssl.c:22:24: fatal error: pyconfig.h: No such file or directory

 #  include <pyconfig.h>

                        ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /PATH/GeoUsage/bin/python3 -c "import setuptools, tokenize;__file__='/PATH/GeoUsage/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/afssalx/18204/pip-4of5z2qy-record/install-record.txt --single-version-externally-managed --compile --install-headers /PATH/GeoUsage/include/site/python3.4 failed with error code 1 in /PATH/GeoUsage/build/cryptography
Storing debug log for failure in /PATH/alx/.pip/pip.log
```

(I removed some paths and replaced it with PATH). Any clues / advice? Thanks

**Comment by tomkralidis** [comment]
In this case you need the `python-dev` system (not pip) dependency/requirement.  So on Ubuntu/Debian systems:

```bash
apt-get install python-dev
```

Note that `requirements-dev.txt` is not required for using GeoUsage per se, yet more for development/packaging.

**Comment by alexandreleroux** [comment]
Thanks, my understanding is that it won't work with users who don't have root access, like myself. Please consider updating the docs to clarify this additional requirement for running the tests. Thanks and closing ticket.
